-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema LEICA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LEICA` ;

-- -----------------------------------------------------
-- Schema LEICA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LEICA` DEFAULT CHARACTER SET utf8 ;
USE `LEICA` ;

-- -----------------------------------------------------
-- Table `LEICA`.`AREA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEICA`.`AREA` ;

CREATE TABLE IF NOT EXISTS `LEICA`.`AREA` (
  `ID_AREA` INT NOT NULL,
  `DESC_AREA` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL COMMENT 'Informática\nTelecomunicaciones\n',
  PRIMARY KEY (`ID_AREA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `LEICA`.`TIPO_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEICA`.`TIPO_USUARIO` ;

CREATE TABLE IF NOT EXISTS `LEICA`.`TIPO_USUARIO` (
  `ID_TIPO_USUARIO` INT NOT NULL,
  `DESC_TIPO_USU` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT 'ADMINISTRADOR\nDOCENTE\nALUMNO',
  PRIMARY KEY (`ID_TIPO_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `LEICA`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEICA`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `LEICA`.`USUARIO` (
  `ID_USU` INT NOT NULL AUTO_INCREMENT,
  `PASS_USU` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `NOM_USU` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `APE_USU` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `EDAD_USU` INT NOT NULL,
  `SEXO_USU` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `FECHA_NAC_USU` DATETIME NOT NULL,
  `TELEFONO_USU` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `CORREO_USU` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `ESTADO_USU` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL COMMENT 'ACTIVO\nINACTIVO\n\n',
  `CARRERA_USU` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT 'Ingeniería Informática\nIngeniería en Telecomunicaciones, Conectividad y Redes\nAnalista Programador\nTelecomunicaciones, Conectividad y Redes',
  `AREA_ID_AREA` INT NOT NULL,
  `TIPO_USUARIO_ID_TIPO_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_USU`, `AREA_ID_AREA`, `TIPO_USUARIO_ID_TIPO_USUARIO`),
  INDEX `fk_USUARIO_AREA1_idx` (`AREA_ID_AREA` ASC),
  INDEX `fk_USUARIO_TIPO_USUARIO1_idx` (`TIPO_USUARIO_ID_TIPO_USUARIO` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `LEICA`.`ASIGNATURA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEICA`.`ASIGNATURA` ;

CREATE TABLE IF NOT EXISTS `LEICA`.`ASIGNATURA` (
  `ID_ASIG` VARCHAR(8) CHARACTER SET 'utf8' NOT NULL,
  `DESC_ASIG` VARCHAR(80) CHARACTER SET 'utf8' NOT NULL,
  `TIPO_ASIG` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `AREA_ID_AREA` INT NOT NULL,
  PRIMARY KEY (`ID_ASIG`, `AREA_ID_AREA`),
  INDEX `fk_ASIGNATURA_AREA1_idx` (`AREA_ID_AREA` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `LEICA`.`LABORATORIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEICA`.`LABORATORIO` ;

CREATE TABLE IF NOT EXISTS `LEICA`.`LABORATORIO` (
  `ID_LAB` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `NOM_LAB` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `DESC_LAB` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `ESTADO_LAB` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL COMMENT 'ESTADO \nDISPONIBLE \nEN MANTENCION\nNO DISPONIBLE',
  `NUMEQUIP_LAB` INT NOT NULL,
  PRIMARY KEY (`ID_LAB`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `LEICA`.`ESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEICA`.`ESTADO` ;

CREATE TABLE IF NOT EXISTS `LEICA`.`ESTADO` (
  `ID_EST` INT NOT NULL,
  `ESTADO_APROB` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT 'APROBADA\nRECHAZADA\nPENDIENTE\n',
  PRIMARY KEY (`ID_EST`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `LEICA`.`SOLICITUD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEICA`.`SOLICITUD` ;

CREATE TABLE IF NOT EXISTS `LEICA`.`SOLICITUD` (
  `ID_SLT` INT NOT NULL AUTO_INCREMENT,
  `FECHA_SLT` DATETIME NOT NULL,
  `HORA_INI_SLT` TIME(6) NOT NULL,
  `HORA_FIN_SLT` TIME(6) NOT NULL,
  `DESC_SLT` VARCHAR(80) CHARACTER SET 'utf8' NOT NULL,
  `ASIGNATURA_ID_ASIG` VARCHAR(8) CHARACTER SET 'utf8' NOT NULL,
  `ASIGNATURA_AREA_ID_AREA` INT NOT NULL,
  `USUARIO_ID_USU` INT NOT NULL,
  `USUARIO_AREA_ID_AREA` INT NOT NULL,
  `LABORATORIO_ID_LAB` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `ESTADO_ID_EST` INT NOT NULL,
  PRIMARY KEY (`ID_SLT`, `ASIGNATURA_ID_ASIG`, `ASIGNATURA_AREA_ID_AREA`, `USUARIO_ID_USU`, `USUARIO_AREA_ID_AREA`),
  INDEX `fk_SOLICITUD_ASIGNATURA1_idx` (`ASIGNATURA_ID_ASIG` ASC, `ASIGNATURA_AREA_ID_AREA` ASC),
  INDEX `fk_SOLICITUD_USUARIO1_idx` (`USUARIO_ID_USU` ASC, `USUARIO_AREA_ID_AREA` ASC),
  INDEX `fk_SOLICITUD_LABORATORIO1_idx` (`LABORATORIO_ID_LAB` ASC),
  INDEX `fk_SOLICITUD_ESTADO1_idx` (`ESTADO_ID_EST` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `LEICA`.`TIPO_MATERIAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEICA`.`TIPO_MATERIAL` ;

CREATE TABLE IF NOT EXISTS `LEICA`.`TIPO_MATERIAL` (
  `ID_TIPO_MATERIAL` INT NOT NULL AUTO_INCREMENT,
  `DESC_TIPO_MATERIAL` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL COMMENT 'INSUMO\nEQUIPAMIENTO',
  PRIMARY KEY (`ID_TIPO_MATERIAL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `LEICA`.`MATERIALES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEICA`.`MATERIALES` ;

CREATE TABLE IF NOT EXISTS `LEICA`.`MATERIALES` (
  `ID_MAT` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `NOM_MAT` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `DESC_MAT` VARCHAR(300) CHARACTER SET 'utf8' NOT NULL,
  `FECHA_REC_MAT` DATETIME NOT NULL,
  `MODELO_MAT` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `MAC_MATERIAL` VARCHAR(50) NULL,
  `ESTADO_MAT` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT 'NUEVO\nE - EXCELENTE\nB - BUENO\nR - REGULAR\nM - MALO\n',
  `UNIDADES` INT NOT NULL,
  `COMENTARIO_MAT` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `TIPO_MATERIAL_ID_TIPO_MATERIAL` INT NOT NULL,
  PRIMARY KEY (`ID_MAT`),
  INDEX `fk_MATERIALES_TIPO_MATERIAL1_idx` (`TIPO_MATERIAL_ID_TIPO_MATERIAL` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `LEICA`.`HIST_SESSION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEICA`.`HIST_SESSION` ;

CREATE TABLE IF NOT EXISTS `LEICA`.`HIST_SESSION` (
  `ID_HIST_SESSION` INT NOT NULL AUTO_INCREMENT,
  `FECHA_INICIO` DATETIME NOT NULL,
  `HORA_INICIO` TIME NOT NULL,
  `ESTADO` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT 'CONECTADO\nDESCONECTADO\n',
  `USUARIO_ID_USU` INT NOT NULL,
  `USUARIO_AREA_ID_AREA` INT NOT NULL,
  `USUARIO_TIPO_USUARIO_ID_TIPO_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_HIST_SESSION`, `USUARIO_ID_USU`, `USUARIO_AREA_ID_AREA`, `USUARIO_TIPO_USUARIO_ID_TIPO_USUARIO`),
  INDEX `fk_HIST_SESSION_USUARIO1_idx` (`USUARIO_ID_USU` ASC, `USUARIO_AREA_ID_AREA` ASC, `USUARIO_TIPO_USUARIO_ID_TIPO_USUARIO` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `LEICA`.`SECCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEICA`.`SECCION` ;

CREATE TABLE IF NOT EXISTS `LEICA`.`SECCION` (
  `ID_SECCION` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `DESC_SECCION` VARCHAR(150) CHARACTER SET 'utf8' NULL,
  `ASIGNATURA_ID_ASIG` VARCHAR(8) CHARACTER SET 'utf8' NOT NULL,
  `ASIGNATURA_AREA_ID_AREA` INT NOT NULL,
  PRIMARY KEY (`ID_SECCION`, `ASIGNATURA_ID_ASIG`, `ASIGNATURA_AREA_ID_AREA`),
  INDEX `fk_SECCION_ASIGNATURA1_idx` (`ASIGNATURA_ID_ASIG` ASC, `ASIGNATURA_AREA_ID_AREA` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `LEICA`.`DETALLE_SOLICITUD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEICA`.`DETALLE_SOLICITUD` ;

CREATE TABLE IF NOT EXISTS `LEICA`.`DETALLE_SOLICITUD` (
  `SOLICITUD_ID_SLT` INT NOT NULL,
  `MATERIALES_ID_MAT` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `CANT_SOLICITADO` INT NOT NULL,
  PRIMARY KEY (`MATERIALES_ID_MAT`, `SOLICITUD_ID_SLT`),
  INDEX `fk_SOLICITUD_has_MATERIALES2_MATERIALES1_idx` (`MATERIALES_ID_MAT` ASC),
  INDEX `fk_SOLICITUD_has_MATERIALES2_SOLICITUD1_idx` (`SOLICITUD_ID_SLT` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
